services:

  express_app:
    build:
      context: https://github.com/etec-integration-project/2025-backend-Inaki-Gongora.git
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network

  frontend:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network: