services:

  mysql_engine:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=zephyr
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - app_network
      
  express_app:
    build:
      context: https://github.com/etec-integration-project/2025-backend-Inaki-Gongora.git
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DB_HOST=mysql_engine
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=zephyr
      - DB_PORT=3306
    networks:
      - app_network
    command: ["node", "app.js"]

  frontend:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network
    environment:
      - REACT_APP_API_URL=http://express_app:3000/api

networks:
  app_network:
