services:

  mysql_engine:
    image: mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - app_network
      
  express_app:
    build:
      context: https://github.com/etec-integration-project/2025-backend-Inaki-Gongora.git
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network
    command: ["node", "app.js"]

  frontend:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network:
